### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by PedrixzZDev** [coredex-source/ForceGL20-1.2x#6]
I tried to run the mod on 1.21.3 and this error occurred
[crash-2024-12-05_09.33.24-client.txt](https://github.com/user-attachments/files/18023640/crash-2024-12-05_09.33.24-client.txt)

**Comment by flydiscohuebr** [comment]
```
Backend API: Mesa Intel(R) HD Graphics (ILK) GL version 2.1 Mesa 24.2.7 (git-3900828265), Intel
```
From what I understand, this mod is useful for video cards that have incomplete OpenGL 3.2, such as the HD 2000 on Windows, since it relaxes the requirements, thus making the game open.
Your video card only supports OpenGL 2.1, so even with the mod it won't work, since there are parts of the game that are written to work with OpenGL 3.2.
As you are on Linux, you can run the game with the parameters.
```
MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150
```
This will force the game to run with OpenGL 3.2 but expect poor performance and broken graphics since software rendering will be used.
Consider upgrading your hardware XD

**Comment by coredex-source** [comment]
Yeah thanks for the reply @flydiscohuebr .. you are mostly right here .. even ogl 3.0 works but ogl 2.1 just crashes the crap out of the game as yes, there are parts written in ogl 3 .. even if you manage to boot the game on ogl 2.1 with the mod you wont be able to use performance mods as they do rely on incomplete but some ogl 3 implementation
